version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-es
    versions:
    - 3.28.0
    - 3.28.1
    - 3.28.10
    - 3.28.11
    - 3.28.13
    - 3.28.14
    - 3.28.16
    - 3.28.18
    - 3.28.2
    - 3.28.22
    - 3.28.23
    - 3.28.24
    - 3.28.25
    - 3.28.26
    - 3.28.4
    - 3.28.5
    - 3.28.8
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
